#!/bin/bash
# Morning HM-CD-instr data collection — fires 10:15 AZ Mon-Fri
# (45 min after US market open at 09:30 ET = 06:30 AZ; gives the scan cycle
#  time to fire several agent iterations.)
#
# Reads cycle wall + per-agent wall times from HM-CD-instr log lines,
# identifies the slowest agent, DRAFTS a migration directive for Captain
# review (per HM-CLOSE-GAP Q3 — auto-generate + HALT, do not auto-ship).

set -uo pipefail
cd ~/autonomous-trader || exit 1

LOG=~/autonomous-trader/logs/trader_error.log
TODAY=$(date +%Y-%m-%d)
DRAFT=~/autonomous-trader/data/scotty_hm_cd_migrate_DRAFT_$TODAY.md

# Grep last 45 min of HM-CD-instr lines (best-effort tail; relies on log
# format from cc5da70 commit which uses [HM-CD-instr] prefix).
CYCLE_LINES=$(grep "HM-CD-instr.*cycle wall" "$LOG" 2>/dev/null | tail -5)
AGENT_LINES=$(grep "HM-CD-instr.*agent=" "$LOG" 2>/dev/null | tail -100)

if [ -z "$AGENT_LINES" ]; then
  curl -fsS -d "⚠️ HM-CD-instr morning fire $TODAY 10:15 AZ — 0 HM-CD-instr log lines. Scan cycle may not be firing during market hours yet. Investigate via: tail -200 logs/trader_error.log | grep CrewScanner" \
    -H "Title: HM-CD-instr morning: 0 data" -H "Priority: high" -H "Tags: warning" \
    https://ntfy.sh/ollietrades-admin > /dev/null 2>&1
  exit 0
fi

# Identify slowest agent by mean wall time
SLOWEST_RAW=$(echo "$AGENT_LINES" | sed -nE 's/.*agent=([^ ]+).*wall=([0-9.]+)s.*/\1 \2/p' \
  | awk '{a[$1]+=$2; c[$1]++} END {for(k in a) printf "%.2f %d %s\n", a[k]/c[k], c[k], k}' \
  | sort -rn)
SLOWEST_LINE=$(echo "$SLOWEST_RAW" | head -1)
SLOWEST_WALL=$(echo "$SLOWEST_LINE" | awk '{print $1}')
SLOWEST_COUNT=$(echo "$SLOWEST_LINE" | awk '{print $2}')
SLOWEST_AGENT=$(echo "$SLOWEST_LINE" | awk '{print $3}')

# Generate DRAFT migration directive
cat > "$DRAFT" <<DRAFT_EOF
# HM-CD-migrate DRAFT — Auto-generated $TODAY 10:15 AZ

**Generated by:** scripts/morning_cd_instr.sh (HM-CLOSE-GAP W4)
**Source data:** logs/trader_error.log, last ~45 min of [HM-CD-instr] entries

## Slowest agent this morning

\`\`\`
$SLOWEST_AGENT
  mean wall:   ${SLOWEST_WALL}s/agent-call
  observed in: $SLOWEST_COUNT cycles
\`\`\`

## Full mean-wall ranking (descending)

\`\`\`
$SLOWEST_RAW
\`\`\`

## Recent cycle wall samples

\`\`\`
$CYCLE_LINES
\`\`\`

## Captain action

If approved, paste a focused HM-CD-migrate directive scoped to $SLOWEST_AGENT
with anchor \`# === HM-CD-migrate ===\`. Migration should target the agent's
specific yfinance/network/DB bottleneck per Polygon-first doctrine.

If $SLOWEST_AGENT's wall time looks within tolerance (e.g., <2s/call for
non-Ollama agents, <30s for Ollama agents), no action needed — log the
data and re-evaluate next session.

## Cross-references

- HM-CD-instr ship commit: cc5da70 (per-agent + cycle wall-time instrumentation)
- Polygon doctrine: CLAUDE.md L86 (Stocks Starter + Options Starter ACTIVE)
- Pattern: HM-CB candles migration (proven Polygon → Alpaca → yfinance fallback)

DRAFT_EOF

# ntfy Captain
curl -fsS \
  -d "🏁 HM-CD-migrate DRAFT ready ($TODAY) — slowest agent: $SLOWEST_AGENT (mean ${SLOWEST_WALL}s, $SLOWEST_COUNT cycles). Review at data/scotty_hm_cd_migrate_DRAFT_$TODAY.md" \
  -H "Title: HM-CD-migrate Draft Ready" \
  -H "Priority: default" \
  -H "Tags: dart" \
  https://ntfy.sh/ollietrades-admin > /dev/null 2>&1 || echo "ntfy POST failed"

echo "[morning_cd_instr] draft generated for $SLOWEST_AGENT (${SLOWEST_WALL}s); ntfy fired"
